sudo: required
services:
  - docker

before_install:
  - docker build -t ercankurtoglu/test1 -f Dockerfile.dev .

script:
  - docker run -e CI=true ercankurtoglu/test1 npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "nmtest1"
  env: "Nmtest1-env"
  bucket_name: "elasticbeanstalk-us-east-1-588738596885"
  bucket_path: "nmtest1"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
